-- AlterTable
ALTER TABLE "Evento" ALTER COLUMN "descricao" DROP NOT NULL,
ALTER COLUMN "inicio" DROP NOT NULL,
ALTER COLUMN "fim" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Tarefa" ALTER COLUMN "titulo" DROP NOT NULL,
ALTER COLUMN "descricao" DROP NOT NULL,
ALTER COLUMN "inicioPrevisto" DROP NOT NULL,
ALTER COLUMN "fimPrevisto" DROP NOT NULL;
